<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 *
 * @author      Webjump Core Team <dev@webjump.com.br>
 * @copyright   2023 Webjump (http://www.webjump.com.br)
 * @license     http://www.webjump.com.br Copyright
 * @link        http://www.webjump.com.br
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>


    <div class="chat_wrapper" data-bind="scope: 'chat_component'">
        <!-- ko template: getTemplate() --> <!-- /ko -->
    </div>


<script type="text/x-magento-init">
    {
        ".chat_wrapper": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>
